dist: xenial

language: python

python:
  - "3.7"

install:
  - pip install -r requirements.txt

script:
  - pytest -v --cov=./todo/ ./tests/

after_sucess:
  - pip install codecov
  - codecov --file .coverage
