dist: xenial

language: python
cache: pip
python:
  - "3.7"

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - rm -rf .coverage htmlcov
  - pytest -v --cov=./todo/ ./tests/

after_sucess:
  - coveralls
