dist: xenial

language: python

python:
  - "3.7"

install:
  - pip install -r requirements.txt

script:
  - pytest -v --cov-report=term --cov=./todo/ ./tests/

after_sucess:
  - pip install coveralls
  - coveralls
