dist: xenial
sudo: true
language: python
cache: pip
python:
  - "3.7"

install:
  - pip install -r requirements.txt

script:
  - pytest -v --pep8 --cov-report term --cov todo tests

after_sucess:
  - coveralls
