dist: xenial

language: python
cache: pip
python:
  - "3.7"

install:
  - pip install -r requirements.txt

script:
  - rm -rf .coverage htmlcov
  - pytest -v --cov-report=xml --cov=./todo/ ./tests/

after_sucess:
  - codecov --file coverage.xml
